#!/bin/bash

#/home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" volume 0.4

touch ~/.lbc

if [[ -f ~/.tr ]]; then rm ~/.tr & touch ~/.lbc
fi

/home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" media play http://media-ice.musicradio.com:80/LBCUK


/home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" volume 0.4
