#!/bin/bash


vol=$(/home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" status | awk -F 'Volume:' '{print $2}' | cut -c4-5 | bc -l)

    if [[ "$vol" -eq "00" ]]; then
      /home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" volume 0.37
      
      
    elif [[ "$vol" -gt "01" ]]; then
      /home/swipe/bin/cast-linux-amd64 --name "Kitchen mini" volume 0
    fi
   
