#!/bin/bash

mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng && rename_xmuted; }
mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng; }
unmute () { "$HOME/bin/mute_radiotray-ng" -u /usr/bin/radiotray-ng; }

# Clean up any obsolete .conkytimer files
if [[ -f ~/.conkytimer ]]; then rm ~/.conkytimer
fi

# Conky countdown timer
conkytimer()
{
#trap "rm ~/.conkytimer" INT

sec=$1
millisecondsToseonds=$(( $1/1000 ))

for (( i = 0; i < $sec; i++ )); do
        # write remaining sec to file
        timer=$((sec-i))
        display="                           ${timer}"
        echo "$display" > ~/.conkytimer
        # wait 1sec
        sleep 1
done

if [[ -f ~/.conkytimer ]]; then rm ~/.conkytimer
fi
}


# check if time is between top of the hour and 6 minutes
check_top_of_the_hour()
{  
   # Get current time in minutes
   currenttime=$(date +%M)
   if [[ "$currenttime" > "00" ]] && [[ "$currenttime" < "07" ]]; then
        
        declare -i adlength=30
        
        mute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0
        
        #~/.conky/conkytimer "$adlength" &
        
        conkytimer "$adlength"
          
        #sleep "$adlength"
        
        unmute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
    
        exit
   fi
}


check_top_of_the_hour

#check_quarter_past_the_hour

#check_bottom_of_the_hour

mute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0

#radio3
#classicfm
#soma

get_adbreak_length() 
{

# Get stream metadata
ffprobe http://media-ice.musicradio.com:80/LBCUK &> "$HOME/stream.txt"

# Cut six digit adbreak length from metadata file and remove any :
#adbreaklength=$(printf '%s' | awk -v RS='[[:blank:]]' '/^ADBREAK_LENGTH_/' "$HOME/stream.txt" | cut -c16-21 | sed 's/://g')

# Cut six digit adbreak length from metadata file from the line beginning with 'StreamUrl'
adbreaklength=$(awk -F 'StreamUrl' '{print $2}' "$HOME/stream.txt" | cut -c25-30)

#Remove any leading 0 digits
#adbreaklength=$((10#$adbreaklength + 1))



# Set as integer and convert from ms to seconds
declare -i ms=$adbreaklength
declare -i value=("$ms"/1000)

echo "$value"

}

seconds=$(get_adbreak_length)

until [ "$seconds" -gt 0 ] || [ "$SECONDS" -gt 180 ]
do 
    get_adbreak_length
    seconds=$(get_adbreak_length)
    sleep 5
done


conkytimer $seconds

#lbc ; 

unmute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
