#!/bin/sh
# Usage: ./toggle_mute3 X X X X X  (where X is no of seconds to mute for)

mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng && rename_xmuted; }
unmute () { "$HOME/bin/mute_radiotray-ng" -u /usr/bin/radiotray-ng && rename_muted; }

mute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0
sleep "$1"

unmute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60 
