#!/bin/sh

mute () { "$HOME/bin/mute_radiotray-ng" -m /usr/bin/radiotray-ng; }
unmute () { "$HOME/bin/mute_radiotray-ng" -u /usr/bin/radiotray-ng; }

# check if time is between top of the hour and 6 minutes
check_top_of_the_hour()
{  
   #Get current time in minutes
   currenttime=$(date +%M)
   if [[ "$currenttime" > "00" ]] && [[ "$currenttime" < "07" ]]; then
        
        declare -i adlength=30
        
        mute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0

        #~/.conky/conkytimer "$adlength" &
          
        sleep "$adlength"
        
        unmute

        qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
    
        exit
   fi
}

check_top_of_the_hour

mute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 0

function get_adbreak_length() 

{

ffprobe http://media-ice.musicradio.com:80/LBCUK &> "$HOME/stream.txt"

adbreaklength=$(printf '%s' | awk -v RS='[[:blank:]]' '/^ADBREAK_LENGTH_/' "$HOME/stream.txt" | cut -c16-21)

declare -i ms=$adbreaklength
declare -i value=("$ms"/1000)

echo "$value"

}


seconds=$(get_adbreak_length)

until [ "$seconds" -gt 0 ]
do 
    get_adbreak_length
    seconds=$(get_adbreak_length)
    sleep 5
done


#echo "$seconds"

sleep "$seconds"

unmute

qdbus org.kde.plasmashell /org/kde/osdService org.kde.osdService.volumeChanged 60
